# config.py

# This file contains the configuration for the analysis script,
# such as file paths and plot settings.

# --- File Paths ---
# New paths to the single, clean data files generated by the ETL script
PROCESSED_TIMESERIES_FILE = 'data/processed/processed_timeseries_data.csv'
PROCESSED_GEO_FILE = 'data/processed/processed_geo_data.csv'

# --- Plot Settings ---
IMAGES_DIR = 'images'
PLOT_WIDTH = 12
PLOT_HEIGHT = 6
# config.py

